### PR TITLE
Add Dockerfile for fegenie deps

### PR DESCRIPTION
**Pull request by note**
First of all - thank you for publishing FeGenie!

I wanted to be able to run FeGenie in different environments with minimal effort so I created a Dockerfile and built an image with FeGenie dependencies [here](https://hub.docker.com/repository/docker/note/fegenie-deps). As a consequence:

1. Users can run FeGenie without installing any of dependencies. So users don't need to have python, R, prodigal etc. - the only dependency is docker. Since docker is available on Windows too it might be a big step towards enabling not so tech-savvy users running FeGenie.
2. It's easier to set up CI build. I created neccessary files in `ci` directory and I have enabled travis build for my fork already. Here's an example output of build trigerred by PR to my fork: https://travis-ci.com/note/FeGenie/builds/148200230

Please note that docker image I pushed to docker hub does not contain FeGenie itself. I didn't know what license FeGenie uses so I was not sure if you mind distributing your code in that way. If you don't mind we can discuss having FeGenie itself in the image too. Both current method and having code in the image have some advantages and disadvantages.

I also included some minor enhancements here are there :)

### CODE REVIEW

**Comment by note** [comment]
Just to clarify - I published docker image with FeGenie dependencies using my account on dockerhub just because that was the only way for me to test it properly. If you are interested in maintaining it by yourself I can walk you through.

Regarding travis-ci - if you want to enable it for your repository you need to activate travis according to https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci (points 1-3, I created `.travis.yml` in my PR already)

**Comment by Arkadiy-Garber** [comment]
Hi there Michal,

Sorry for the super-late response to this pull request. Thanks for using FeGenie, hope it was useful for you.

And mega-thanks for making a Dockerfile for FeGenie!! I think it would be great to have FeGenie available through Docker! If the offer still stands, I would definitely be interested in discussing ways that we can make that happen. I am actually not really familiar with Docker, so would be open to either 1) having it on your account (although that might be difficult to maintain if I am routinely updating it here), or 2) maintaining it myself. In the latter case, i would appreciate you walking me through how to go about doing that :)

Thanks again, and apologies for the late response!
Arkadiy

**Comment by note** [comment]
Hey Arkadiy,

Thanks for replying and no worries about reply time :)

When I was creating that PR I was not really aware of what Conda does. Whereas there are some differences between what Conda and Docker do, I think in FeGenie case they solve the same issue - how to install all the dependencies of the package.

With that in mind I recreated all other changes except of Dockerfile in https://github.com/note/FeGenie/pull/3. It's a PR against by own branch to demonstrate "All checks have passed" section. You would need to enable TravisCI to make it work in PRs to your repository.

The main advantage of having this kind of test is better confidence that your changes do not break previous results. And in case you want to introduce breaking change you can always just change expected results.

I have no idea if you find it useful, I found it useful when introducing my small changes here.

Regarding Docker - I think it's not unusual to have a different repository in different organisation only for sake of Dockerfile. Given that you are probably familiar with Conda and I am more familiar with Docker it may make sense to keep it in a separate repository. That said - my repository would not need to even contain FeGenie source code - it just need to have contain code provisioning dependencies.

**Comment by Arkadiy-Garber** [comment]
Hi Michal,

Thanks for the note. I agree, it seems to make sense to keep the Dockerfile in a separate repository. I am generally okay with you organizing that in whichever way you find most convenient/efficient. So the Dockerfile links to the FeGenie repo and treats it as another dependency?

Please let me know if there are any issue running it. I don't have Docker installed currently, but have always imagined that it was similar to Conda. So I think I might give it a try one of these days and attempt running FeGenie using the Dockerfile you created.

Just as an FYI, there were some minor changes to the FeGenie.py script that I made after you created the pull request, and I just resolved those minor conflicts, and am about to merge the pull request.

Thanks!
Arkadiy

**Comment by Arkadiy-Garber** [comment]
One additional quick note:

An important change that I implemented since the initial pull request that you submitted is the removal of the -hmm_lib flag. Now, it is required that FeGenie is added to the user's $PATH, and the script uses `which FeGenie.py` to locate the _hmms/iron_ directory. Not sure if that has any effects on running the program with Docker. For example, with the Conda installation, the `hmms/iron` path is added to the conda virtual environment, and FeGenie.py is, by default, in the user's path in that virtual environment. So, can be activated by entering `FeGenie.py` from any directory.

Anyway, just a heads up in case that might cause any issues.

Thanks,
Arkadiy

**Comment by note** [comment]
> So the Dockerfile links to the FeGenie repo and treats it as another dependency?

At the moment it just declares FeGenie's dependencies. User is assumed to clone FeGenie repository and mount it with `-v` option.

There are 2 other options: 

1) docker image can distribute FeGenie itself. For many cases it's the most convenient option but there are 2 disadvantages: you couple that way versioning of docker image with versioning of FeGenie (which in general is good but since FeGenie do not have releases or versioning scheme) and it makes it more difficult for users to inspect the source of the script (I guess in case of small Python script users may try to adjust script slightly etc.)
2) docker image may have a script cloning FeGenie. It might be the best option on the long run.

> I don't have Docker installed currently, but have always imagined that it was similar to Conda

Yeah, the aspect of declaring all dependencies is very similar between them. However Docker has additional concept of a container, it's an isolated process running in its own namespace - it has its own, limited view of filesystem and networking. I can imagine Docker to be more involving but the basics are not complex, if you ever try it just read a bit about mounting volumes.

That said, Docker also has some advantages - e.g. it was easy for me to also include R and all R packages with it. I don't think it's easy with conda as R packages are distributed as source. In case of Docker I build them once in Dockerfile and now every user can just download compiled images from Docker Hub.

> Now, it is required that FeGenie is added to the user's $PATH, and the script uses which FeGenie.py to locate the hmms/iron directory. Not sure if that has any effects on running the program with Docker.

Thanks for letting know. It will not work in current version of Dockerfile I added. It's not difficult to add though. I will try to take a look in following days.

**Comment by Arkadiy-Garber** [comment]
Hi Michal,

Thanks for the note. That actually clears some things up and helps me to understand how Docker works. Sounds pretty cool. Dealing with Rscript and R packages has actually been particularly difficult. So I'm glad to hear that you are able to build them in a Dockerfile and the user doesn't have to worry about it. Makes things MUCH easier.

With regard to the 2 options that you described, I agree. Sounds like option 2 would be the easiest way to go about it, and insure that the user always deals with the latest version of FeGenie. Alternatively, it also doesn't seem unreasonable to expect the user to clone FeGenie themselves and mount it with -v. Either way is fine by me! If you have the time to spare, definitely feel free to add to the docker image a script to clone FeGenie and add it to the path.

Much appreciated! If it is fine by you, I will add a line to the README acknowledging your contributions.

Thanks,
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Hey Michał,

Hope all is well with you. Just as an FYI, we are getting close to publishing a FeGenie update, where you are listed in the Acknowledgments. Also, a Bioconda contributor was able to create a Conda recipe for FeGenie. So in the README, I wanted to list all three installation instructions: Conda, Docker, and manual.

When you get a chance, could you please send me the commands that one would need to run to install the FeGenie Dockerfile. Also, if this helps, I added a license to the FeGenie repo: GNU Affero General Public License v3.0.

Thanks again for your help!
Arkadiy

**Comment by note** [comment]
Hi Arkadiy,

Thanks a lot for mentioning me in Acknowledgments!

There is a section about how to run FeGenie with Docker already. When testing it today I realized there were some changes in how some parameters are being provided. I updated README + test scripts here https://github.com/Arkadiy-Garber/FeGenie/pull/28. Let me know if you meant something else.

Best,
Michał

**Comment by Arkadiy-Garber** [comment]
Ah, that's right! That is exactly what I was thinking off. Forgot that was there...obviously I have not scrolled through my own README in a while. This will certainly do.

Thanks!
Arkadiy

**Pull request merged**
